# Generated by Django 4.0.3 on 2022-03-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('1', 'Books'), ('2', 'Movies'), ('3', 'Music'), ('4', 'Games'), ('5', 'Software'), ('9', 'Other')], max_length=1)),
                ('product_slug', models.SlugField()),
                ('price', models.PositiveIntegerField()),
                ('desc', models.TextField(blank=True, max_length=1000, null=True)),
                ('product_pic', models.ImageField(blank=True, default='products/no-img.jpg', null=True, upload_to='products/pictures')),
                ('content_url', models.URLField(blank=True, null=True)),
                ('content_file', models.FileField(blank=True, null=True, upload_to='products/files')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
