# Generated by Django 4.0.3 on 2022-04-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_slug',
            new_name='slug',
        ),
    ]
